# Introduction to Matrices and Linear Algebra

## Using Numpy and Sympy to create Matrices

In [3]:
import numpy as np
import sympy as sy
import random

## Create matrices manually 

- **Numpy**

In [4]:
np.array([[1, 2],[4, 5]])

array([[1, 2],
       [4, 5]])

In [5]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

- **Sympy**

In [6]:
sy.Matrix([[1,2], [4,5]])

Matrix([
[1, 2],
[4, 5]])

In [12]:
sy.Matrix([[1],[2],[3]])

Matrix([
[1],
[2],
[3]])

In [8]:
sy.Matrix([4,5,6])

Matrix([
[4],
[5],
[6]])

In [9]:
sy.Matrix([[4,5,6]])

Matrix([[4, 5, 6]])

## Generating matrices using the random library

- **Numpy**

In [19]:
np.random.randint(2, 8, size=(2, 2))

array([[2, 3],
       [5, 4]])

In [25]:
np.random.randint(-2, 4, size=(1, 5))

array([[ 1,  1, -1,  0,  2]])

In [22]:
np.random.randint(-2, 4, size=(5, 1))

array([[-1],
       [-2],
       [ 3],
       [ 1],
       [ 1]])

- **Sympy**

In [23]:
sy.Matrix(np.random.randint(2, 8, size=(2, 2)))

Matrix([
[6, 7],
[2, 3]])

In [27]:
sy.Matrix(np.random.randint(-2, 4, size=(1, 5)))

Matrix([[1, 1, -2, -2, 2]])

In [29]:
sy.Matrix(np.random.randint(-2, 4, size=5))

Matrix([
[ 0],
[-2],
[ 1],
[ 0],
[-1]])

### Creating special matrices

 - **Identity matrix**

 - **Numpy**

In [31]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [33]:
np.eye(3, 4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [36]:
np.eye(3, 4, dtype=int, k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

- **Sympy**

In [37]:
sy.eye(2)

Matrix([
[1, 0],
[0, 1]])

In [38]:
sy.eye(2, 3)

Matrix([
[1, 0, 0],
[0, 1, 0]])

In [42]:
sy.eye(4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [43]:
sy.eye(3, 4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])

 - **Zeros Matrix**

- **Numpy**

In [46]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.zeros((4, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
np.zeros((4, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

- **Sympy**

In [50]:
sy.zeros(2)

Matrix([
[0, 0],
[0, 0]])

In [51]:
sy.zeros(3,4)

Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

 - **Ones Matrix**

- **Numpy**

In [53]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [54]:
np.ones((4,1), dtype=int)

array([[1],
       [1],
       [1],
       [1]])

In [55]:
np.ones((4, 4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- **Sympy**

In [65]:
sy.ones(4)

Matrix([
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1]])

In [57]:
sy.ones(2, 3)

Matrix([
[1, 1, 1],
[1, 1, 1]])

- **Diagonal Matrix**

- **Numpy**

In [58]:
np.diag([1, 3, 6])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [63]:
x = np.arange(2, 10).reshape(2,4)
print(x)
np.diag(x)

[[2 3 4 5]
 [6 7 8 9]]


array([2, 7])

- **Sympy**

In [66]:
sy.diag(1, 2, 3)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [67]:
sy.diag([1, 2, 3])

Matrix([
[1],
[2],
[3]])

In [69]:
sy.diag(*[1, 2, 3])

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [70]:
sy.diag([1, 2, 3], unpack=True)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])