In [4]:
import numpy as np
import random

N = np.random.randn(1,4,3)
N

array([[[ 0.20839458,  1.70351372,  1.97174341],
        [-0.63935132, -0.06848456, -0.85157464],
        [-2.0689846 , -0.57049015, -1.4042798 ],
        [-0.09590347,  0.68733256, -0.11123906]]])

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Creation of 1D array
#### np.arange(start, stop, step) and np.linspace

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [14]:
 np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [15]:
np.linspace(2, 10, num=8)

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [16]:
np.linspace(2, 10, num=8, dtype=int)

array([ 2,  3,  4,  5,  6,  7,  8, 10])

In [17]:
np.linspace(2, 10, num=8, dtype=int, endpoint=False)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.matrix([[1, 3], [4, 6]])

matrix([[1, 3],
        [4, 6]])